protocol file
mime text/*, application/json
action launch --type=overlay --cwd=current ${EDITOR} ${FILE_PATH}

protocol file
ext md, csv, toml, conf, json, py, sh
action launch --type=overlay --cwd=current ${EDITOR} ${FILE_PATH}
